name: Demo Docker Action
on:
  workflow_dispatch:

jobs:
  calling_docker_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container
        id: hello-action
        uses: ./hello-world-docker-action
        with:
           who-to-greet: "@GerardoRamosDev"

      - name: Output from the cotainer
        run: echo "The time was ${{ step.hello-action.outputs.time }}"
